chore: increase ci message readability

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,8 +31,8 @@ jobs:
     - name: Format check
       run: |
         (npm run format:check && echo -e "\033[32mFORMAT CHECK PASSED\033[0m") || \
-        (echo -e "\033[31m\nFORMAT CHECK FAILED\033[0m" && exit 1)
+        (echo -e "\n\033[31mFORMAT CHECK FAILED\033[0m" && exit 1)
     - name: Lint
       run: |
         (npm run lint && echo -e "\033[32mESLINT PASSED\033[0m") || \
-        (echo -e "\033[31m\nESLINT FAILED\033[0m" && exit 1)
+        (echo -e "\n\033[31mESLINT FAILED\033[0m" && exit 1)
